---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - name: Install System Packages
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items:
          - nginx
          - rabbitmq-server
          - python-pip
          - python
          - python-dev
          - gcc
          - libncurses5-dev
          - libffi-dev
          - build-essential
          - postgresql
          - libpq-dev
          - htop
          - vim
          - redis-server
          - python-psycopg2
      notify: Start Everything

    - name: Install Virtualenv
      pip: name=virtualenv state=present

    - name: Install Python Requirements
      pip:
        requirements: /var/rmndin/requirements.txt
        virtualenv: /var/rmndinenv
        virtualenv_python: python3

    - name: Copy nginx configuration
      template:
        src: files/rmndin
        dest: /etc/nginx/sites-available/rmndin
        owner: root
        group: sudo
        mode: 0644

    - name: Deactivate default nginx config
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Link new config
      file: src=/etc/nginx/sites-available/rmndin dest=/etc/nginx/sites-enabled/rmndin state=link
      notify: Restart Nginx

  handlers:
    - name: Start Nginx
      service: name=nginx state=started
      listen: Start Everything

    - name: Restart Nginx
      service: name=nginx state=restarted

    - name: Start RabbitMQ
      service: name=rabbitmq-server state=started
      listen: Start Everything

- hosts: all
  become: yes
  become_user: postgres
  gather_facts: no
  tasks:
    - name: ensure database is created
      postgresql_db: name=rmndindb
    - name: ensure user has access to database
      postgresql_user: db=rmndindb name=rmndinuser password=rmndinpassword priv=ALL
    - name: ensure user does not have unnecessary privilege
      postgresql_user: name=rmndinuser role_attr_flags=NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the database
      postgresql_privs: db=rmndindb role=PUBLIC type=database priv=ALL state=absent

