"""empty message

Revision ID: 5732e007e036
Revises: ac6f47c9fa13
Create Date: 2017-01-23 04:31:22.974771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5732e007e036'
down_revision = 'ac6f47c9fa13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
