"""Add cascades for User -> UserContact and Reminder -> UserContact

Revision ID: b34ae5edb932
Revises: e5cafc12208a
Create Date: 2017-02-04 20:20:09.383082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34ae5edb932'
down_revision = 'e5cafc12208a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'reminder_user_id_fkey', 'reminder', type_='foreignkey')
    op.create_foreign_key(None, 'reminder', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'reminder_contact_association_reminder_id_fkey', 'reminder_contact_association', type_='foreignkey')
    op.drop_constraint(u'reminder_contact_association_user_contact_id_fkey', 'reminder_contact_association', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_contact_association', 'user_contact', ['user_contact_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'reminder_contact_association', 'reminder', ['reminder_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'user_contact_user_id_fkey', 'user_contact', type_='foreignkey')
    op.create_foreign_key(None, 'user_contact', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_contact', type_='foreignkey')
    op.create_foreign_key(u'user_contact_user_id_fkey', 'user_contact', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'reminder_contact_association', type_='foreignkey')
    op.drop_constraint(None, 'reminder_contact_association', type_='foreignkey')
    op.create_foreign_key(u'reminder_contact_association_user_contact_id_fkey', 'reminder_contact_association', 'user_contact', ['user_contact_id'], ['id'])
    op.create_foreign_key(u'reminder_contact_association_reminder_id_fkey', 'reminder_contact_association', 'reminder', ['reminder_id'], ['id'])
    op.drop_constraint(None, 'reminder', type_='foreignkey')
    op.create_foreign_key(u'reminder_user_id_fkey', 'reminder', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
