"""Make url a manditory column and add note

Revision ID: cbf21a8bcaa5
Revises: fa74c46cc44e
Create Date: 2017-02-04 07:33:33.249897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf21a8bcaa5'
down_revision = 'fa74c46cc44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('note', sa.String(), nullable=True))
    op.add_column('reminder', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('reminder', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reminder', 'url')
    op.drop_column('reminder', 'note')
    # ### end Alembic commands ###
