"""empty message

Revision ID: d08bb1db0e09
Revises: fa43eac13962
Create Date: 2017-01-17 23:38:43.915180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08bb1db0e09'
down_revision = 'fa43eac13962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('task_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder', 'task_id')
    # ### end Alembic commands ###
