"""Add reminder_contact many-to-many association

Revision ID: fa74c46cc44e
Revises: 29b0a49bfa22
Create Date: 2017-02-04 03:59:49.337736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa74c46cc44e'
down_revision = '29b0a49bfa22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_contact_association',
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('user_contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ),
    sa.ForeignKeyConstraint(['user_contact_id'], ['user_contact.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_contact_association')
    # ### end Alembic commands ###
