"""empty message

Revision ID: 02702d8035a0
Revises: 5732e007e036
Create Date: 2017-01-26 01:39:04.954046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02702d8035a0'
down_revision = '5732e007e036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    delivery_method_enum = postgresql.ENUM('email', 'reddit', name='delivery_method_enum')
    delivery_method_enum.create(op.get_bind())
    op.add_column('reminder', sa.Column('delivery_method', sa.Enum('email', 'reddit', name='delivery_method_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder', 'delivery_method')
    # ### end Alembic commands ###
