"""Add UserContact model

Revision ID: 221efb505803
Revises: 02702d8035a0
Create Date: 2017-01-29 20:49:46.122706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221efb505803'
down_revision = '02702d8035a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contact',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('method', sa.Enum('email', 'reddit', name='deliverymethodenum'), nullable=False),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_contact')
    # ### end Alembic commands ###
